### ISSUE TITLE
pass-thru is using 'idbKeyVal.delete', should be 'idbKeyVal.del'

### ISSUE THREAD

**Issue by MagRelo** [HenrikJoreteg/money-clip#2]
At https://github.com/HenrikJoreteg/money-clip/blob/master/index.js#L4:

`
export const del = idbKeyVal.delete
`

I think it should be 'idbKeyVal.del'(?)

idb-keyval docs: https://github.com/jakearchibald/idb-keyval#del

**Comment by HenrikJoreteg** [comment]
Hi @MagRelo 👋 

This was actually intentional just because `delete` is a reserved word in JS and I like to be able to destructure parts of it like this:

```js
import { del } from 'money-clip'
```

if it were delete, that'd cause linting issues, etc.

**Comment by MagRelo** [comment]
Hi! : ) I'm sorry, it *is* working. I was working on a forked version, maybe i changed something, my bad!

Sorry to push my luck but but I can't tell *how* your code is working - maybe you can explain(?)

It looks like idb-keyval is always exporting a function named 'del' 
`export { Store, get, set, del, clear, keys };` 
(https://github.com/jakearchibald/idb-keyval/blob/master/dist/idb-keyval.mjs#L64) 

...but you are using 'delete' (?)

`export const del = idbKeyVal.delete`
(https://github.com/HenrikJoreteg/money-clip/blob/master/index.js#L4)

Sorry for my confusion; great lib!

**Comment by HenrikJoreteg** [comment]
No worries! @MagRelo the underlying lib calls it `delete`, but I'm renaming it to `del` by exporting `delete` as `del`

**Comment by MagRelo** [comment]
Ah! different version of 'idb-keyval' - I was looking at 'idb-keyval' version 3.0.2; it looks like the function has been renamed. 'idb-keyval' now also calls it 'del'.  Sorry!

**Comment by HenrikJoreteg** [comment]
@MagRelo oh, i didn't realize he had updated it. I'll make a note to bring this up to speed, thanks!
